### ISSUE TITLE
Got the latest build but Hot Reload is still now working.

### ISSUE THREAD

**Issue by shresthasans** [johndatserakis/modern-webpack-starter#1]

**Comment by johndatserakis** [comment]
Ok I'll look into this very soon. Can you triple-check that you have all the new updated files? I've recently fixed the hot reload - but maybe something isn't working right.

**Comment by johndatserakis** [comment]
Hey there - I took a look, but I couldn't find an issue with hot reload in the latest build.

I cloned a fresh copy and then changed a css value in the program css file: `./src/assets/css/components/_program.scss`. I saw my change updated live. Then I changed the button text in the main.js fle: `./src/main.js` and it hot reloaded the changes without issue.

Sorry but I can't seem to reproduce the issue here - let me know if I should try another use case, I could be missing something of course. Thanks.

**Comment by johndatserakis** [comment]
Hey I'll close this for now - let me know if you are still having issues and I'll reopen it. Thank you!
